build:
  uri: https://github.com/theashiot/elytron-examples/tree/main
  contextDir: simple-webapp-saml
deploy:
  volumes:
    - name: saml-keystore-volume
      secret:
        secretName: simple-webapp-saml-secret
  volumeMounts:
    - name: saml-keystore-volume
      mountPath: /etc/keycloak-saml-secret-volume
      readOnly: true
